name: Publish Docker Image
on: 
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Set Docker Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: akath19/drone-sonar-plugin
    - name: Build and Push
      uses: docker/build-action@v3
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
    - name: Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Version ${{ setps.meta.output.tags }}