name: Publish Docker Image
on: 
  push:
    tags:
      - 'v*'
jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Set Docker Metadata
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: akath19/drone-sonar-plugin
    - name: Build and Push
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
    - name: Get Tag For Release
      uses: battila7/get-version-action@v2
      id: get_version
    - name: Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: v${{ steps.get_version.outputs.version }}
